### ISSUE TITLE
Is it possible to update the text ?

### ISSUE THREAD

**Issue by HalidCisse** [Cokile/CCActivityIndicatorView#2]

**Comment by Cokile** [comment]
Hey HalidCisse,

I am sorry that I am not quite understand what do you mean.

Do you mean that when the HUD is shown with some text and update the text to tell users about the current state of the task?

**Comment by HalidCisse** [comment]
exactly !

**Comment by Cokile** [comment]
Hey HalidCisse,

Unfortunately, it is impossible now. But I will add this feature in the next version.

**Comment by Cokile** [comment]
Hey HalidCisse,

Now you can use `UpdateWithText:shimmering:` to update text when using `showWithText:shimmering:`.

PS. Do not forget to update the pod to the latest version.
