### ISSUE TITLE
Mistyped Animation Type

### ISSUE THREAD

**Issue by moghtaderi** [Cokile/CCActivityIndicatorView#4]
In file "CCActivityHUD.h" line 94:

**@property CCActivityHUDAppearAnimationType disappearAnimationType;**
 
should be:

**@property CCActivityHUDDisappearAnimationType disappearAnimationType;**

**Comment by moghtaderi** [comment]
Also, I can't get the indicator color to change, and couldn't find anyplace where it's being set or used... Can you please verify?

It would be great to add the option of setting the color for overlay and/or blur amount.

**Comment by Cokile** [comment]
Hey, @moghtaderi 

Thanks for your feedback. I will take a look of the typo and the color issue.

**Comment by Cokile** [comment]
Hey, @moghtaderi 
I have fix the typo and the indicator color bug in v2.1.7 .
For the option of setting the color for overlay and/or blur amount, I will take it into consideration in the future release. Or you can create a Pull Request for it  ;-)
